# Generated by Django 5.2.8 on 2025-11-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('PS4', 'PlayStation 4'), ('XBOX_SERIES', 'Xbox Series X/S'), ('XBOX_ONE', 'Xbox One'), ('SWITCH', 'Nintendo Switch'), ('MULTI', 'Multiplataforma')], default='PC', max_length=20, verbose_name='Plataforma')),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('RPG', 'RPG'), ('DEPORTES', 'Deportes'), ('ESTRATEGIA', 'Estrategia'), ('SIMULACION', 'Simulación'), ('CARRERAS', 'Carreras'), ('SHOOTER', 'Shooter'), ('TERROR', 'Terror'), ('PUZZLE', 'Puzzle')], default='ACCION', max_length=20, verbose_name='Género')),
                ('desarrollador', models.CharField(blank=True, max_length=200, null=True, verbose_name='Desarrollador')),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
                'ordering': ['-created_at'],
            },
        ),
    ]
